### ISSUE TITLE
Stack dump with {org.clojure/clojure         {:mvn/version  "1.10.1"} 

### ISSUE THREAD

**Issue by sbnl** [r0man/ring-cors#30]
deps.edn with {org.clojure/clojure         {:mvn/version  "1.10.1"} creates stack trace but 1.10.0 does not. 

Removing   (wrap-cors ...  also removes the problem.  Is this something to do with regex?
  
Exception in thread "main" java.lang.ClassCastException: clojure.pprint.proxy$java.io.Writer$IDeref$PrettyFlush$4923d848 cannot be cast to clojure.pprint.PrettyFlush
	at clojure.pprint$pretty_writer$fn__8066.invoke(pretty_writer.clj:392)
	at clojure.pprint.proxy$java.io.Writer$IDeref$PrettyFlush$4923d848.flush(Unknown Source)
	at clojure.core$flush.invokeStatic(core.clj:3711)
	at clojure.core$flush.invoke(core.clj:3705)
	at clojure.core$prn.invokeStatic(core.clj:3722)
	at clojure.core$prn.doInvoke(core.clj:3714)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.pprint$pprint.invokeStatic(pprint_base.clj:252)
	at clojure.pprint$pprint.invoke(pprint_base.clj:241)
	at clojure.pprint$pprint.invokeStatic(pprint_base.clj:245)
	at clojure.pprint$pprint.invoke(pprint_base.clj:241)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.main$report_error$fn__6582$fn__6583.invoke(main.clj:603)
	at clojure.main$report_error$fn__6582.invoke(main.clj:602)
	at clojure.main$report_error.invokeStatic(main.clj:601)
	at clojure.main$report_error.doInvoke(main.clj:584)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at clojure.main$main.invokeStatic(main.clj:666)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)

**Comment by sveri** [comment]
I have version "0.1.13" running with a 1.10.1 clojure version and cannot see that stacktrace. Maybe something else is going on?
